### PR TITLE
fix: Perform an HEAD call to get file info before the actual GET / fixed unit-tests

### LINKED ISSUE #9: Test suite does not pass
I am currently in the process of packaging `arduino-cli` in Debian and I tried to run the tests of this library but it didn't pass. Here is the log:

```console
$ go version
$go version go1.22.11 linux/amd64
$ go test
--- FAIL: TestDownload (0.26s)
    require.go:157: 
        	Error Trace:	downloader_test.go:38
        	Error:      	Not equal: 
        	            	expected: 8052
        	            	actual  : -1
        	Test:       	TestDownload
--- FAIL: TestNoResume (0.01s)
    require.go:157: 
        	Error Trace:	downloader_test.go:85
        	Error:      	Not equal: 
        	            	expected: 8052
        	            	actual  : -1
        	Test:       	TestNoResume
ERROR: Get "asd://go.bug.st/test.txt": unsupported protocol scheme "asd"
ERROR: setting up HTTP request: parse "://": missing protocol scheme
callback called 326 times
8
16
24
32
40
48
56
64
72
80
89
98
107
116
125
134
143
152
161
170
170
Server stopped
--- FAIL: TestContextCancelation (3.00s)
    require.go:794: 
        	Error Trace:	downloader_test.go:220
        	Error:      	Received unexpected error:
        	            	context canceled
        	Test:       	TestContextCancelation
FAIL
exit status 1
FAIL	go.bug.st/downloader/v2	4.397s
```

### PR DESCRIPTION
**Pull request by cmaglie**
This should solve part of the issue with servers not supporting Range headers.

Fixes #9

### CODE REVIEW

File: downloader.go [hunk 1]
```diff
@@ -137,20 +138,29 @@ func DownloadWithConfig(file string, reqURL string, config Config, options ...Do
...
 
+	// Setup the actual GET request
+	req, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
 	if err != nil {
 		return nil, fmt.Errorf("setting up HTTP request: %s", err)
 	}
 
 	var completed int64
-	if !noResume {
+	if !noResume && serverAcceptsRanges {
```
Comment (lucarin91) [inline downloader.go:163]: I would add a short circuit somewhere that, if we have the whole file, i.e., `size == completed`. Also, because in the range header, you cannot have a size that is equal to or greater than the total file size.

**Review by lucarin91 — CHANGES_REQUESTED** [review]

File: downloader.go (hunk 1 above)
Comment (cmaglie) [reply downloader.go:163]: Turns out to be quite an involved change.
I've added a unit test that checks this condition, and without the shortcut, the downloader seems to behave correctly anyway.

I'll keep this change request in another PR so it can be discussed better.

Comment (cmaglie) [reply downloader.go:163]: https://github.com/bugst/go-downloader/pull/14
